ALTER TABLE "Blog" ADD COLUMN IF NOT EXISTS "authorDoctorId" TEXT;
ALTER TABLE "Blog" ADD CONSTRAINT "Blog_authorDoctorId_fkey" FOREIGN KEY ("authorDoctorId") REFERENCES "Doctor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
